name: MyWorkflow     # le nom du workflow
on: [push].                # l’event qui déclenche le workflow

jobs:                      # les jobs
  myJob1:                        # Le nom du job
    runs-on: ubuntu-latest.            # l’environnement sur lequel tourne un job
    
    
    steps:                             # les steps à executer
      - uses: actions/checkout@v2   # checkout le projet courrant dans le runner de job1
        
      - name: Use Node.js 12.x.    #nom facultatitif pour cette action  
        uses: actions/setup-node@v2 # install nodeJs version 12
        with:
          node-version: 12.x
          
      - name: Build # le nom est obligatoir pour les actions de ligne de commande
        run: npm install. # execute la ligne de commande 

  myJob2:              # un autre job
    runs-on: ubuntu-latest
    needs: myJob1      # attend la fin du job1 pour s'executer
    Steps:
        - if:error==0.       # lance cette step si aucune erreur n'a été détectée auparavant
         name: Echo 
         run: |            # execute un script sur plusieur ligne de commande
            echo “fin du job2”
            echo “build OK”
           
