name: NameOfMyWorkflow     # le nom du workflow
on: [push].                # l’event qui déclenche le workflow

jobs:                      # les jobs
  nameOfMyJob1:                        # Le nom du job
    runs-on: ubuntu-latest.            # l’environnement sur lequel tourne un job
    steps:                             # les steps à executer
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Build
        run: gradle build

  nameOfMyJob2:              # un autre job
    runs-on: ubuntu-latest
    needs: nameOfMyJob1      # attend la fin du job1 pour s'executer
    Steps:
        - if:error==0.       # lance cette step si aucune erreur n'a été détectée auparavant
         name: Echo
         run: echo “build OK”
